export default {
    icons: {
        ic_back: require('res/images/icons/ic_back.png'),
        ic_next: require('res/images/icons/ic_next.png'),
        ic_facetime: require('res/images/icons/ic_facetime.png'),
        ic_close: require('res/images/icons/ic_close.png'),
        ic_eye_black: require('res/images/icons/eye_black.png'),
        ic_hide_pass: require('res/images/icons/ic_hide_pass.png'),
        ic_up_down: require('res/images/icons/ic_up_down.png'),
        ic_hospital: require('res/images/icons/ic_hospital.png'),
        ic_notification: require('res/images/icons/ic_notification.png'),
        ic_user: require('res/images/icons/ic_user.png'),
        ic_next_arrow: require('res/images/icons/ic_next_arrow.png'),
        ic_back_arrow: require('res/images/icons/ic_back_arrow.png'),
        drug: {
            ic_prescription: require('res/images/icons/drug/ic_prescription.png'),
            ic_cart: require('res/images/icons/drug/ic_cart.png'),
            ic_search: require('res/images/icons/drug/ic_search.png'),
        },
        home: {
            add: require('res/images/icons/home/add.png'),
            address: require('res/images/icons/home/address.png'),
            doctor: require('res/images/icons/home/doctor.png'),
            ehealt: require('res/images/icons/home/ehealt.png'),
            list: require('res/images/icons/home/list.png'),
            ticker: require('res/images/icons/home/ticker.png'),
            ic_home: require('res/images/icons/home/ic_home.png'),
            ic_account: require('res/images/icons/home/ic_account.png'),
            ic_noti: require('res/images/icons/home/ic_noti.png'),
            ic_calendar: require('res/images/icons/home/ic_calendar.png'),
            ic_doctor: require('res/images/icons/home/ic_doctor.png'),
            ic_dropdown: require('res/images/icons/home/ic_dropdown.png'),
            ic_drug: require('res/images/icons/home/ic_drug.png'),
            ic_ehealth: require('res/images/icons/home/ic_ehealth.png'),
            ic_flamingo: require('res/images/icons/home/ic_flamingo.png'),
            ic_warning: require('res/images/icons/home/ic_warning.png'),
        },
        follow_health: {
            ic_note: require('res/images/icons/followHealth/ic_note.png'),
            ic_success: require('res/images/icons/followHealth/ic_success.png'),
            ic_warning: require('res/images/icons/followHealth/ic_warning.png'),
            ic_danger: require('res/images/icons/followHealth/ic_danger.png'),
        },
    },
    default: {
        logo: require('res/images/defaults/logo.png'),
        isofh: require('res/images/defaults/isofh.png'),
        drug: require('res/images/defaults/drug.jpg'),
    }
}