// const Host = '192.168.1.21'
const Host = '178.128.97.142'

export default {
	VERSION: '1.1.1',
	
	API_SERVER: 'http://' + Host + ':3010',
	SOCKET_SERVER: 'http://' + Host + ':3011',
	MEDIA_SERVER: 'http://' + Host + ':3012',

	SESSION_STATUS_WAITING: 1,
	SESSION_STATUS_ACTIVE: 2,
	SESSION_STATUS_COMPLETE: 3,
	SESSION_STATUS_CANCEL: 4,
	SESSION_STATUS_REJECT: 5,

	MESSAGE_TYPE_TEXT: 1,
	MESSAGE_TYPE_PHOTO: 2,
	MESSAGE_TYPE_VIDEO: 3,

	SOCKET_EVENT_PATIENT_DOCTOR_SESSION_REQUEST: 'patient:doctor:session:request',
	SOCKET_EVENT_USER_SESSION_MESSAGE_NEW: 'user:session:message:new',
	SOCKET_EVENT_USER_WEBRTC_CANDIDATE: 'user:webrtc:candidate',
	SOCKET_EVENT_USER_WEBRTC_INVITE: 'user:webrtc:invite',
	SOCKET_EVENT_USER_WEBRTC_ACCEPT: 'user:webrtc:accept',
	SOCKET_EVENT_USER_WEBRTC_OFFER: 'user:webrtc:offer',
	SOCKET_EVENT_USER_WEBRTC_ANSWER: 'user:webrtc:answer',
	SOCKET_EVENT_USER_WEBRTC_FINISH: 'user:webrtc:finish'
}