export default {
    AuthenStack:'AuthenStack', // stack login
    HomeStack:'HomeStack',     // stack home
    DrawerStack:'DrawerStack',
    LoginScreen:'Đăng nhập', 
    HomeScreen:'Trang chủ',
    RegisterScreen:'Đăng ký',
    ForgotPasswordScreen:'Quên mật khẩu',
    SplashScreen:'SplashScreen',
    AccountScreen:'Tài khoản',
    NotificationScreen:'NotificationScreen',
    IntoScreen:'IntoScreen',
    ScheduleScreen:'Lịch khám',
    FollowHealthScreen:'Theo dõi sức khỏe',
    DetailScheduleScreen:'Chi tiết lịch khám',
    NoteDoctorScreen:'Lời dặn của bác sỹ',
    DrugScreen:'Đơn thuốc',
    BookingDrugScreen:'Đặt mua thuốc theo đơn',
    ConfirmBookingScreen:'Xác nhận đơn thuốc',
    MessageScreen:'Chi tiết tin nhắn',
    ListDoctorScreen:'Danh sách bác sĩ',
    VideoCallScreen:'VideoCallScreen',
    ListHospitalScreen:'Danh sách bệnh viện',
    HospitalScreen:'Danh sách bệnh viện',
    InputPhoneScreen:'Xác thực số điện thoại',
    OtpScreen:'OtpScreen',
    TestScreen:'TestScreen',
    TestTodayScreen:'Kiểm tra tình trạng sức khỏe',
    ReportScreen:'Dấu hiệu bất thường',
    TestResultScreen:'TestResultScreen',
    ProfileScreen:'Thông tin cá nhân',
    MyDrugScreen:'Đơn thuốc của bạn',
    CityScreen:'Tỉnh / Thành phố',
    DistrictScreen:'Quận / Huyện',
    CommunesScreen:'Xã / Phường',
    ChangePassScreen:'Đổi mật khẩu',
    DetailDrugScreen:'Chi tiết đơn thuốc',
    TabDoctor:'TabDoctor',
    HistoryMessage:'HistoryMessage'
}